python train.py \
    --dataset_root /datasets/graspnet \
    --camera kinect \
    --model_name gsnet_dev \
    --log_dir logs/gsnet_dev \
    --learning_rate 0.001 \
    --max_epoch 20 \
    --batch_size 1 \
    --backbone resunet \
    --single_sample \
    --num_point 15000 \
    --train_split train \
    --single_sample